/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package tsynik.xposed.mod.gapps;

public final class BuildConfig {
    public static final boolean DEBUG = Boolean.parseBoolean("false");
    public static final String APPLICATION_ID = "tsynik.xposed.mod.gapps";
    public static final String BUILD_TYPE = "release";
    public static final String FLAVOR = "";
    public static final int VERSION_CODE = 1;
    public static final String VERSION_NAME = "1.0";
}
